version: "3.7"
services:
  dev:
    build: .
    command: npm run dev
    volumes:
      - .:/build
      - /node_modules
    ports:
      - "8080:80"
  prod:
    build: .
    ports:
      - "8080:80"
